# Generated by Django 4.0.3 on 2022-03-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_crawled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('press', models.CharField(max_length=15, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('comment', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('content', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_crawled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('press', models.CharField(max_length=15, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('content', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section_crawled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('press', models.CharField(max_length=15, null=True)),
                ('section', models.CharField(max_length=10, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('content', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('news_id', models.ForeignKey(db_column='news', on_delete=django.db.models.deletion.CASCADE, to='summ.popular_crawled')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('news_id', models.ForeignKey(db_column='news', on_delete=django.db.models.deletion.CASCADE, to='summ.popular_crawled')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('news_id', models.ForeignKey(db_column='news', on_delete=django.db.models.deletion.CASCADE, to='summ.popular_crawled')),
            ],
        ),
    ]
