# Generated by Django 4.0.3 on 2022-03-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_keyword',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='popular_keyword',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='section_keyword',
            name='news_id',
        ),
        migrations.AddField(
            model_name='comment_keyword',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.comment_crawled'),
        ),
        migrations.AddField(
            model_name='popular_keyword',
            name='popular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.popular_crawled'),
        ),
        migrations.AddField(
            model_name='section_keyword',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.section_crawled'),
        ),
        migrations.AlterField(
            model_name='comment_crawled',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment_keyword',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='popular_crawled',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='popular_keyword',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section_crawled',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section_keyword',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
