# Generated by Django 4.0.3 on 2022-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0002_remove_comment_keyword_news_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_crawled',
            name='reading',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popular_crawled',
            name='reading',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section_crawled',
            name='reading',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section_keyword',
            name='section_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
