# Generated by Django 4.0.3 on 2022-05-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0003_comment_crawled_reading_popular_crawled_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_keyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Total_News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('press', models.DateField(null=True)),
                ('section', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('comment', models.IntegerField(null=True)),
                ('reading', models.IntegerField(null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_keyword',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='popular_keyword',
            name='popular',
        ),
        migrations.DeleteModel(
            name='Comment_crawled',
        ),
        migrations.DeleteModel(
            name='Comment_keyword',
        ),
        migrations.DeleteModel(
            name='Popular_crawled',
        ),
        migrations.DeleteModel(
            name='Popular_keyword',
        ),
        migrations.AddField(
            model_name='total_keyword',
            name='popular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.total_news'),
        ),
    ]
