# Generated by Django 4.0.3 on 2022-05-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0004_total_keyword_total_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_keyword',
            name='popular',
        ),
    ]
