# Generated by Django 4.0.3 on 2022-05-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0005_remove_total_keyword_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_keyword',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.total_news'),
        ),
        migrations.AddField(
            model_name='total_news',
            name='cluster_label',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='total_news',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='total_news',
            name='rangking',
            field=models.IntegerField(null=True),
        ),
    ]
