# Generated by Django 4.0.4 on 2022-06-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0006_total_keyword_total_total_news_cluster_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_crawled',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='total_news',
            name='rangking',
        ),
        migrations.AddField(
            model_name='total_keyword',
            name='section_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='total_news',
            name='press',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
