# Generated by Django 4.0.4 on 2022-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0007_remove_section_crawled_ranking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_keyword',
            name='section',
        ),
        migrations.AddField(
            model_name='total_keyword',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Section_crawled',
        ),
        migrations.DeleteModel(
            name='Section_keyword',
        ),
    ]
