# Generated by Django 4.0.3 on 2022-06-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0008_remove_section_keyword_section_total_keyword_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Three_News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster_label', models.IntegerField(null=True)),
                ('comment', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('press', models.CharField(max_length=20, null=True)),
                ('reading', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Two_News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster_label', models.IntegerField(null=True)),
                ('comment', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('press', models.CharField(max_length=20, null=True)),
                ('reading', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Two_keyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=20, null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('score', models.FloatField(null=True)),
                ('total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.total_news')),
            ],
        ),
        migrations.CreateModel(
            name='Three_keyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=20, null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('score', models.FloatField(null=True)),
                ('total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.total_news')),
            ],
        ),
    ]
