# Generated by Django 4.0.3 on 2022-06-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0009_three_news_two_news_two_keyword_three_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='three_keyword',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.three_news'),
        ),
        migrations.AlterField(
            model_name='two_keyword',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summ.two_news'),
        ),
    ]
