# Generated by Django 4.0.3 on 2022-06-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0010_alter_three_keyword_total_alter_two_keyword_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='three_keyword',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_key', to='summ.three_news'),
        ),
        migrations.AlterField(
            model_name='total_keyword',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_key', to='summ.total_news'),
        ),
        migrations.AlterField(
            model_name='two_keyword',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_key', to='summ.two_news'),
        ),
    ]
