# Generated by Django 4.0.3 on 2022-03-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_crawled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
